create database CARDB;

USE CARDB;

CREATE TABLE BRANDINFO
(BRANDID INTEGER PRIMARY KEY,
BRANDNAME VARCHAR(25));

CREATE TABLE MODELINFO
(MODELINFOID integer primary key auto_increment,
BRANDID integer,
MODELNAME varchar(25),
FOREIGN KEY (BRANDID) REFERENCES BRANDINFO(BRANDID));

SELECT * FROM MODELINFO;

SELECT * FROM BRANDINFO;

ALTER TABLE MODELINFO AUTO_INCREMENT=100;

INSERT INTO BRANDINFO
VALUES(002, 'AUDI');

INSERT INTO MODELINFO
VALUES(002,001,'M SERIES');

INSERT INTO MODELINFO
VALUES(003,001,'S SERIES');

INSERT INTO MODELINFO
VALUES(004,002,'Q4');

INSERT INTO MODELINFO (BRANDID, MODELNAME)
VALUES(1,'X SERIES');

INSERT INTO MODELINFO
VALUES(005,002,'R5');

/*This is where I started*/





